/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminTimetableRouteImport } from './routes/admin/timetable'
import { Route as AdminTeachingTasksRouteImport } from './routes/admin/teaching-tasks'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminTeacherProfilesRouteImport } from './routes/admin/teacher-profiles'
import { Route as AdminModelTrainingRouteImport } from './routes/admin/model-training'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminConstraintEditorRouteImport } from './routes/admin/constraint-editor'
import { Route as AdminClassroomsRouteImport } from './routes/admin/classrooms'
import { Route as AdminClassGroupsRouteImport } from './routes/admin/class-groups'
import { Route as AdminAllocationRouteImport } from './routes/admin/allocation'
import { Route as AdminAdjustmentRouteImport } from './routes/admin/adjustment'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachingTasksRoute = AdminTeachingTasksRouteImport.update({
  id: '/teaching-tasks',
  path: '/teaching-tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeacherProfilesRoute = AdminTeacherProfilesRouteImport.update({
  id: '/teacher-profiles',
  path: '/teacher-profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelTrainingRoute = AdminModelTrainingRouteImport.update({
  id: '/model-training',
  path: '/model-training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConstraintEditorRoute = AdminConstraintEditorRouteImport.update({
  id: '/constraint-editor',
  path: '/constraint-editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassroomsRoute = AdminClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassGroupsRoute = AdminClassGroupsRouteImport.update({
  id: '/class-groups',
  path: '/class-groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdjustmentRoute = AdminAdjustmentRouteImport.update({
  id: '/adjustment',
  path: '/adjustment',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/adjustment': typeof AdminAdjustmentRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/class-groups': typeof AdminClassGroupsRoute
  '/admin/classrooms': typeof AdminClassroomsRoute
  '/admin/constraint-editor': typeof AdminConstraintEditorRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/model-training': typeof AdminModelTrainingRoute
  '/admin/teacher-profiles': typeof AdminTeacherProfilesRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-tasks': typeof AdminTeachingTasksRoute
  '/admin/timetable': typeof AdminTimetableRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/adjustment': typeof AdminAdjustmentRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/class-groups': typeof AdminClassGroupsRoute
  '/admin/classrooms': typeof AdminClassroomsRoute
  '/admin/constraint-editor': typeof AdminConstraintEditorRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/model-training': typeof AdminModelTrainingRoute
  '/admin/teacher-profiles': typeof AdminTeacherProfilesRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-tasks': typeof AdminTeachingTasksRoute
  '/admin/timetable': typeof AdminTimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/adjustment': typeof AdminAdjustmentRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/class-groups': typeof AdminClassGroupsRoute
  '/admin/classrooms': typeof AdminClassroomsRoute
  '/admin/constraint-editor': typeof AdminConstraintEditorRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/model-training': typeof AdminModelTrainingRoute
  '/admin/teacher-profiles': typeof AdminTeacherProfilesRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-tasks': typeof AdminTeachingTasksRoute
  '/admin/timetable': typeof AdminTimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/admin/adjustment'
    | '/admin/allocation'
    | '/admin/class-groups'
    | '/admin/classrooms'
    | '/admin/constraint-editor'
    | '/admin/courses'
    | '/admin/model-training'
    | '/admin/teacher-profiles'
    | '/admin/teachers'
    | '/admin/teaching-tasks'
    | '/admin/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/admin/adjustment'
    | '/admin/allocation'
    | '/admin/class-groups'
    | '/admin/classrooms'
    | '/admin/constraint-editor'
    | '/admin/courses'
    | '/admin/model-training'
    | '/admin/teacher-profiles'
    | '/admin/teachers'
    | '/admin/teaching-tasks'
    | '/admin/timetable'
  id:
    | '__root__'
    | '/admin'
    | '/login'
    | '/admin/adjustment'
    | '/admin/allocation'
    | '/admin/class-groups'
    | '/admin/classrooms'
    | '/admin/constraint-editor'
    | '/admin/courses'
    | '/admin/model-training'
    | '/admin/teacher-profiles'
    | '/admin/teachers'
    | '/admin/teaching-tasks'
    | '/admin/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teaching-tasks': {
      id: '/admin/teaching-tasks'
      path: '/teaching-tasks'
      fullPath: '/admin/teaching-tasks'
      preLoaderRoute: typeof AdminTeachingTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teacher-profiles': {
      id: '/admin/teacher-profiles'
      path: '/teacher-profiles'
      fullPath: '/admin/teacher-profiles'
      preLoaderRoute: typeof AdminTeacherProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/model-training': {
      id: '/admin/model-training'
      path: '/model-training'
      fullPath: '/admin/model-training'
      preLoaderRoute: typeof AdminModelTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/constraint-editor': {
      id: '/admin/constraint-editor'
      path: '/constraint-editor'
      fullPath: '/admin/constraint-editor'
      preLoaderRoute: typeof AdminConstraintEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classrooms': {
      id: '/admin/classrooms'
      path: '/classrooms'
      fullPath: '/admin/classrooms'
      preLoaderRoute: typeof AdminClassroomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/class-groups': {
      id: '/admin/class-groups'
      path: '/class-groups'
      fullPath: '/admin/class-groups'
      preLoaderRoute: typeof AdminClassGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allocation': {
      id: '/admin/allocation'
      path: '/allocation'
      fullPath: '/admin/allocation'
      preLoaderRoute: typeof AdminAllocationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adjustment': {
      id: '/admin/adjustment'
      path: '/adjustment'
      fullPath: '/admin/adjustment'
      preLoaderRoute: typeof AdminAdjustmentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdjustmentRoute: typeof AdminAdjustmentRoute
  AdminAllocationRoute: typeof AdminAllocationRoute
  AdminClassGroupsRoute: typeof AdminClassGroupsRoute
  AdminClassroomsRoute: typeof AdminClassroomsRoute
  AdminConstraintEditorRoute: typeof AdminConstraintEditorRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminModelTrainingRoute: typeof AdminModelTrainingRoute
  AdminTeacherProfilesRoute: typeof AdminTeacherProfilesRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTeachingTasksRoute: typeof AdminTeachingTasksRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdjustmentRoute: AdminAdjustmentRoute,
  AdminAllocationRoute: AdminAllocationRoute,
  AdminClassGroupsRoute: AdminClassGroupsRoute,
  AdminClassroomsRoute: AdminClassroomsRoute,
  AdminConstraintEditorRoute: AdminConstraintEditorRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminModelTrainingRoute: AdminModelTrainingRoute,
  AdminTeacherProfilesRoute: AdminTeacherProfilesRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTeachingTasksRoute: AdminTeachingTasksRoute,
  AdminTimetableRoute: AdminTimetableRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
