#!/usr/bin/env python3
"""Remove teaching tasks that belong to anomalous course codes.

Default behavior is a dry run. For safety, the default deletion scope is removing
matching teaching tasks from one allocation task, not deleting global teaching_task
rows.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

PROJECT_DIR = Path(__file__).resolve().parents[2]
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from ml.db.config import connect, load_db_config  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Remove teaching tasks by anomalous course_code list from CSV/JSONL/JSON."
    )
    parser.add_argument("input", type=Path, help="CSV/JSONL/JSON file generated by analyze_teaching_task_anomalies.py")
    parser.add_argument(
        "--allocation-task-id",
        type=int,
        help="Remove matching teaching tasks only from this allocation task. Recommended.",
    )
    parser.add_argument(
        "--scope",
        choices=("allocation-task", "mark-inactive", "hard-delete"),
        default="allocation-task",
        help="allocation-task removes links; mark-inactive updates teaching_task.status; hard-delete deletes rows.",
    )
    parser.add_argument("--apply", action="store_true", help="Actually execute changes. Without this, only prints dry-run report.")
    parser.add_argument("--output", type=Path, help="Optional JSON report path.")
    return parser.parse_args()


def load_course_codes(path: Path) -> list[str]:
    if not path.exists():
        raise FileNotFoundError(path)

    suffix = path.suffix.lower()
    codes: set[str] = set()

    if suffix == ".csv":
        with path.open(newline="", encoding="utf-8") as file:
            for row in csv.DictReader(file):
                code = (row.get("course_code") or "").strip()
                if code:
                    codes.add(code)
    elif suffix == ".jsonl":
        with path.open(encoding="utf-8") as file:
            for line in file:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                code = str(row.get("course_code") or "").strip()
                if code:
                    codes.add(code)
    elif suffix == ".json":
        payload = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(payload, dict):
            records = payload.get("course_anomalies") or payload.get("items") or []
        elif isinstance(payload, list):
            records = payload
        else:
            records = []
        for row in records:
            if isinstance(row, dict):
                code = str(row.get("course_code") or "").strip()
                if code:
                    codes.add(code)
    else:
        raise ValueError(f"Unsupported input file type: {suffix}. Use .csv, .jsonl, or .json")

    return sorted(codes)


def placeholders(values: list[Any]) -> str:
    return ", ".join(["%s"] * len(values))


def fetch_matching_tasks(connection, course_codes: list[str], allocation_task_id: int | None) -> list[dict[str, Any]]:
    if not course_codes:
        return []

    params: list[Any] = list(course_codes)
    allocation_join = ""
    allocation_select = "NULL AS allocation_task_id,"
    if allocation_task_id is not None:
        allocation_join = "JOIN allocation_task_teaching_task attt ON attt.teaching_task_id = tt.id"
        allocation_select = "attt.allocation_task_id,"
        params.append(allocation_task_id)
    allocation_filter = "AND attt.allocation_task_id = %s" if allocation_task_id is not None else ""
    sql = f"""
        SELECT
            {allocation_select}
            tt.id AS teaching_task_id,
            tt.status,
            c.code AS course_code,
            c.name AS course_name,
            c.course_type,
            tt.total_hours,
            tt.primary_teacher_id,
            t.name AS teacher_name,
            COUNT(DISTINCT cg.id) AS class_group_count,
            GROUP_CONCAT(DISTINCT cg.name ORDER BY cg.id SEPARATOR ' / ') AS class_group_names
        FROM teaching_task tt
        JOIN course c ON c.id = tt.course_id
        JOIN teacher t ON t.id = tt.primary_teacher_id
        {allocation_join}
        LEFT JOIN teaching_task_class_group ttcg ON ttcg.teaching_task_id = tt.id
        LEFT JOIN class_group cg ON cg.id = ttcg.class_group_id
        WHERE c.code IN ({placeholders(course_codes)})
        {allocation_filter}
        GROUP BY
            allocation_task_id, tt.id, tt.status, c.code, c.name, c.course_type,
            tt.total_hours, tt.primary_teacher_id, t.name
        ORDER BY c.code, tt.id
    """
    with connection.cursor() as cursor:
        cursor.execute(sql, tuple(params))
        return list(cursor.fetchall())


def execute_removal(connection, task_ids: list[int], allocation_task_id: int | None, scope: str) -> int:
    if not task_ids:
        return 0

    affected = 0
    with connection.cursor() as cursor:
        if scope == "allocation-task":
            if allocation_task_id is None:
                raise ValueError("--allocation-task-id is required when --scope allocation-task")
            cursor.execute(
                f"""
                DELETE FROM allocation_task_teaching_task
                WHERE allocation_task_id = %s
                  AND teaching_task_id IN ({placeholders(task_ids)})
                """,
                tuple([allocation_task_id, *task_ids]),
            )
            affected += int(cursor.rowcount or 0)
        elif scope == "mark-inactive":
            cursor.execute(
                f"""
                UPDATE teaching_task
                SET status = 'INACTIVE'
                WHERE id IN ({placeholders(task_ids)})
                """,
                tuple(task_ids),
            )
            affected += int(cursor.rowcount or 0)
        elif scope == "hard-delete":
            task_placeholders = placeholders(task_ids)
            cursor.execute(
                f"""
                DELETE FROM conflict_check_result
                WHERE biz_type = 'ALLOCATION_ITEM'
                  AND biz_id IN (
                      SELECT id FROM allocation_item
                      WHERE teaching_task_id IN ({task_placeholders})
                  )
                """,
                tuple(task_ids),
            )
            affected += int(cursor.rowcount or 0)
            cursor.execute(
                f"""
                DELETE FROM allocation_item_adjustment_log
                WHERE teaching_task_id IN ({task_placeholders})
                   OR item_id IN (
                       SELECT id FROM allocation_item
                       WHERE teaching_task_id IN ({task_placeholders})
                   )
                """,
                tuple([*task_ids, *task_ids]),
            )
            affected += int(cursor.rowcount or 0)
            cursor.execute(
                f"DELETE FROM allocation_item WHERE teaching_task_id IN ({task_placeholders})",
                tuple(task_ids),
            )
            affected += int(cursor.rowcount or 0)
            cursor.execute(
                f"DELETE FROM teaching_task_class_group WHERE teaching_task_id IN ({task_placeholders})",
                tuple(task_ids),
            )
            affected += int(cursor.rowcount or 0)
            cursor.execute(
                f"DELETE FROM allocation_task_teaching_task WHERE teaching_task_id IN ({task_placeholders})",
                tuple(task_ids),
            )
            affected += int(cursor.rowcount or 0)
            cursor.execute(
                f"DELETE FROM teaching_task WHERE id IN ({task_placeholders})",
                tuple(task_ids),
            )
            affected += int(cursor.rowcount or 0)
        else:
            raise ValueError(f"Unsupported scope: {scope}")
    connection.commit()
    return affected


def build_report(course_codes: list[str], rows: list[dict[str, Any]], scope: str, applied: bool, affected_rows: int) -> dict[str, Any]:
    task_ids = sorted({int(row["teaching_task_id"]) for row in rows})
    courses: dict[str, dict[str, Any]] = {}
    for row in rows:
        code = str(row.get("course_code") or "")
        item = courses.setdefault(
            code,
            {
                "course_code": code,
                "course_name": row.get("course_name") or "",
                "course_type": row.get("course_type") or "",
                "task_count": 0,
                "total_hours": 0,
                "teaching_task_ids": [],
            },
        )
        item["task_count"] += 1
        item["total_hours"] += int(row.get("total_hours") or 0)
        item["teaching_task_ids"].append(int(row["teaching_task_id"]))

    return {
        "applied": applied,
        "scope": scope,
        "input_course_code_count": len(course_codes),
        "matched_course_count": len(courses),
        "matched_teaching_task_count": len(task_ids),
        "affected_rows": affected_rows,
        "course_codes": course_codes,
        "teaching_task_ids": task_ids,
        "courses": sorted(courses.values(), key=lambda item: (-item["task_count"], item["course_code"])),
    }


def main() -> None:
    args = parse_args()
    if args.scope == "allocation-task" and args.allocation_task_id is None:
        raise SystemExit("--allocation-task-id is required for --scope allocation-task")
    if args.scope == "hard-delete" and not args.apply:
        print("WARNING: hard-delete selected, but this is still a dry run because --apply was not provided.", file=sys.stderr)

    course_codes = load_course_codes(args.input)
    with connect(load_db_config()) as connection:
        rows = fetch_matching_tasks(connection, course_codes, args.allocation_task_id)
        task_ids = sorted({int(row["teaching_task_id"]) for row in rows})
        affected_rows = execute_removal(connection, task_ids, args.allocation_task_id, args.scope) if args.apply else 0

    report = build_report(course_codes, rows, args.scope, args.apply, affected_rows)
    output = json.dumps(report, ensure_ascii=False, indent=2)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output, encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
